version: "3"
services:
  whale_1:
    image: ubuntu
    command: bash -c "date +%s > timenow.dat && tail -F dummyfile.txt"
    environment:
      - testy_1=failing
  whale_2:
    image: ubuntu
    command: bash -c "date +%s > timenow.dat && tail -F dummyfile.txt"
    environment:
      - testy_2=enthused
  whale_3:
    image: ubuntu
    command: bash -c "date +%s > timenow.dat && tail -F dummyfile.txt"
    environment:
      - testy_3=baby_yoda
  whale_4:
    image: ubuntu
    command: bash -c "tail -F dummyfile.txt"
    environment:
      - testy_4=coronavirus
  whale_5:
    image: 2f6ef4a20cf6
    command: bash -c "tail -F dummyfile.txt"
    environment:
      - testy_5=NOOOPE
# build images
# docker-compose up -d

#_______

# KILL EVERYTHING
# docker container kill $(docker ps -q)

#THEN

# remove:
# docker container rm $(docker ps -a -q)

#_______

# docker ps (check container name)
#
# exec into container:
# docker exec -it <container ID> bash

# access value(see if env variable is available):
# echo $<name of variable>

#________

#container 2:
#1583885093

#container 1:
#1583885092
