version: "3"
services:
  whale_1:
    image: ubuntu
    command: bash -c "date +%s > timenow.dat && tail -F dummyfile.txt"
    environment:
      - WORD=failing
      - RACE_START=20
      - RACE_DURATION=60
  whale_2:
    image: ubuntu
    command: bash -c "date +%s > timenow.dat && tail -F dummyfile.txt"
    environment:
      - WORD=enthused
      - RACE_START=20
      - RACE_DURATION=60
  whale_3:
    image: ubuntu
    command: bash -c "date +%s > timenow.dat && tail -F dummyfile.txt"
    environment:
      - WORD=babyyoda
      - RACE_START=20
      - RACE_DURATION=60
  whale_4:
    image: ubuntu
    command: bash -c "tail -F dummyfile.txt"
    environment:
      - WORD=failing
      - RACE_START=20
      - RACE_DURATION=60
  whale_5:
    image: d6f9a05fa0fb
    command: bash -c "tail -F dummyfile.txt"
    environment:
      - WORD=failing
      - RACE_START=20
      - RACE_DURATION=60
# build image:
# docker build .
# docker-compose up -d

#_______

# KILL EVERYTHING
# docker container kill $(docker ps -q)

#THEN

# remove:
# docker container rm $(docker ps -a -q)

#_______

# docker ps (check container name)
#
# exec into container:
# docker exec -it <container ID> bash

# access value(see if env variable is available):
# echo $<name of variable>

#________

#container 2:
#1583885093

#container 1:
#1583885092
