services:
  whale_0:
    command: bash -c "python3 main.py"
    environment:
    - WORD=dog
    - RACE_START=1591761585
    - RACE_DURATION=1000
    image: df7d3c1453c7
  whale_1:
    command: bash -c "python3 main.py"
    environment:
    - WORD=computer
    - RACE_START=1591761585
    - RACE_DURATION=1000
    image: df7d3c1453c7
  whale_2:
    command: bash -c "python3 main.py"
    environment:
    - WORD=protest
    - RACE_START=1591761585
    - RACE_DURATION=1000
    image: df7d3c1453c7
version: '3'
