services:
  whale_0:
    command: bash -c "python3 main.py"
    environment:
    - WORD=dog
    - RACE_START=1591146201
    - RACE_DURATION=1000
    image: 3679bdbfe1a1
  whale_1:
    command: bash -c "python3 main.py"
    environment:
    - WORD=computer
    - RACE_START=1591146201
    - RACE_DURATION=1000
    image: 3679bdbfe1a1
  whale_2:
    command: bash -c "python3 main.py"
    environment:
    - WORD=protest
    - RACE_START=1591146201
    - RACE_DURATION=1000
    image: 3679bdbfe1a1
version: '3'
