services:
  whale_0:
    command: bash -c "python3 main.py"
    environment:
    - WORD=dog
    - RACE_START=1592341602
    - RACE_DURATION=1000
    image: 4b9fb1e496f3
  whale_1:
    command: bash -c "python3 main.py"
    environment:
    - WORD=computer
    - RACE_START=1592341602
    - RACE_DURATION=1000
    image: 4b9fb1e496f3
  whale_2:
    command: bash -c "python3 main.py"
    environment:
    - WORD=protest
    - RACE_START=1592341602
    - RACE_DURATION=1000
    image: 4b9fb1e496f3
version: '3'
