services:
  whale_0:
    command: bash -c "python3 main.py"
    environment:
    - WORD=pants
    - RACE_START=1602031882
    - RACE_DURATION=10
    - WHALENUMBER=0
    image: 0c54aa44a916
  whale_1:
    command: bash -c "python3 main.py"
    environment:
    - WORD=or
    - RACE_START=1602031882
    - RACE_DURATION=10
    - WHALENUMBER=1
    image: 0c54aa44a916
  whale_2:
    command: bash -c "python3 main.py"
    environment:
    - WORD=words
    - RACE_START=1602031882
    - RACE_DURATION=10
    - WHALENUMBER=2
    image: 0c54aa44a916
version: '3'
